### ISSUE TITLE
setters do not consider bitlength

### ISSUE THREAD

**Issue by LECAN** [mifefr/Consent-String-SDK-PHP#21]
**Describe the bug**
Creating consent string using setters do not consider length found in constant BINARY_CONFIG.
For example :
 
`setVersion(1)` will generate the bitstring "1" instead of "000001"
This changes completely the base64 encoded string at the end. And once this one is decoded, we cannot retrieve any correct data. 

**To Reproduce**

```
        $base64IAB = 'BOXhscYOXhscYACABDENAE4AAAAAwQgA';
        $consentTest = new ConsentCookie( $base64IAB );

        $cc = new ConsentCookie();

        $cc
            ->setVersion($consentTest->getVersion())
            ->setCreated($consentTest->getCreated())
            ->setLastUpdated($consentTest->getLastUpdated())
            ->setCmpId($consentTest->getCmpId())
            ->setCmpVersion($consentTest->getCmpVersion())
            ->setConsentScreen($consentTest->getConsentScreen())
            ->setConsentLanguage($consentTest->getConsentLanguage())
            ->setVendorListVersion($consentTest->getVendorListVersion())
            ->setMaxVendorId($consentTest->getMaxVendorId())
            ->setBitField($consentTest->getBitField())
            ->setPurposesAllowed($consentTest->getPurposesAllowed())
            ->setEncodingType(ConsentCookie::ENCODINGTYPE_BITFIELD);

        var_dump($consentTest->toBase64() == 'BOXhscYOXhscYACABDENAE4AAAAAwQgA');
        var_dump($cc->toBase64() == 'BOXhscYOXhscYACABDENAE4AAAAAwQgA');
```

**Expected behavior**
The format and length of the bitstring (at least without BitField), should stay the same in order to retrieve data.

To quickly test a solution I created a function to resize bit string called in setters : 

```
    public function setVersion($version)
    {
         /* ... */
         $this->version = $this->sizeBits($this->version, self::BINARY_CONFIG['version']['length']);
         return $this;
     }

    private function sizeBits($value, $length) {

        while (strlen($value) < $length) {
            $value = "0" . $value;
        }

        return $value;
    }
```
I hope I did not miss something on how to use the library. But to me, it seems to work properly after this quick fix ( that would certainly need a better implementation :) )

**Comment by Roffray** [comment]
Hi @LECAN,

there was indeed some data length check in the setters that had not been done yet, they have now been added.

Thank you for the reminder !.
